### ISSUE TITLE
Não envia mensagem - Firefox

### ISSUE THREAD

**Issue by giselebrugger** [EduardoKrausME/mod_superchat#1]
Olá Kraus, parabéns pelo projeto. Está excelente.Gostaria de reportar um bug no envio de mensagens usando firefox 42 - linux . Digito a mensagem e ao clicar no botaõ nada acontece.
Habiliei o debug do webdeveloper mas não acusa nenhum erro.
No Chrome está OK

**Comment by eduardokraus** [comment]
Resolvido
